# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1653b4a00d7e9b4b82d73f616719718f4666b816053751de5b061a5b33b360010d0e8ad7e0b5c819d4534d1d19418cbc82ad7768014001ec188c41ac9af9c605

test:
  secret_key_base: ed274d1ab2fecccd029be177de162622f78e1870e9c9a501a03cfc22c72eac162cb5acbf7bd7fd9ea5f0e9570f528c769caaa9cda05f738a058d45ff7110eb4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
